# Generated by Django 4.2.20 on 2025-06-02 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_interno', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('modelo', models.CharField(max_length=100)),
                ('serie', models.CharField(max_length=100)),
                ('fabricante', models.CharField(max_length=100)),
                ('año_fabricacion', models.IntegerField(blank=True, null=True)),
                ('potencia', models.CharField(blank=True, max_length=50, null=True)),
                ('capacidad', models.CharField(blank=True, max_length=100, null=True)),
                ('ubicacion_fisica', models.CharField(max_length=100)),
                ('seccion', models.CharField(choices=[('SOLDADURA', 'Soldadura'), ('MAQUINADO', 'Maquinado'), ('PROTOTIPADO', 'Prototipado'), ('PLASTICOS', 'Plásticos'), ('FUNDICION', 'Fundición'), ('SUJECION', 'Sujeción'), ('TRANSPORTE', 'Transporte')], max_length=20)),
                ('tipo_equipo', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('OPERATIVO', 'Operativo'), ('MANTENIMIENTO', 'Mantenimiento'), ('FUERA_SERVICIO', 'Fuera de Servicio')], max_length=20)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='equipos/')),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('responsable', models.CharField(max_length=100)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('identificador', models.CharField(max_length=50)),
                ('ubicacion', models.CharField(max_length=200)),
                ('responsable', models.CharField(max_length=100)),
                ('colaborador', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Sección',
                'verbose_name_plural': 'Secciones',
            },
        ),
    ]
