# Generated by Django 4.2.20 on 2025-06-06 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='codigo_udb',
            field=models.TextField(blank=True, help_text='Formato: EMI - LPZ\\n1-22386\\nAÑO', max_length=100, null=True, verbose_name='Código Unidad de Disposición de Bienes'),
        ),
    ]
