# Generated by Django 4.2.20 on 2025-06-06 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0002_equipo_codigo_udb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='codigo_udb',
            field=models.CharField(blank=True, help_text='Formato: EMI - LPZ [NÚMERO] [AÑO] - Ejemplo: EMI - LPZ 1-22386 2025', max_length=100, null=True, verbose_name='Código Unidad de Disposición de Bienes'),
        ),
    ]
