# Generated by Django 4.2.20 on 2025-06-06 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0003_alter_equipo_codigo_udb'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='udb_numero',
            field=models.CharField(default='Desconocido', help_text='Ejemplo: 1-22386', max_length=20, verbose_name='Número de Disposición'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipo',
            name='udb_unidad',
            field=models.CharField(choices=[('LPZ', 'LPZ'), ('SCZ', 'SCZ'), ('CBAA', 'CBAA'), ('RIB', 'RIB'), ('TROP', 'TROP')], default='LPZ', max_length=5, verbose_name='Unidad EMI'),
        ),
    ]
