# Generated by Django 4.2.20 on 2025-06-10 02:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0004_equipo_udb_numero_equipo_udb_unidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='amperaje',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Amperaje'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='caudal_aire',
            field=models.IntegerField(blank=True, null=True, verbose_name='Caudal de Aire (L/min)'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='consumo_electrico',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Consumo Eléctrico (kW)'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='epp_requerido',
            field=models.TextField(blank=True, null=True, verbose_name='Equipos de Protección Personal'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='esquema_electrico',
            field=models.FileField(blank=True, null=True, upload_to='documentos/esquemas/', verbose_name='Esquema Eléctrico'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='fases',
            field=models.CharField(blank=True, choices=[('Monofásico', 'Monofásico'), ('Bifásico', 'Bifásico'), ('Trifásico', 'Trifásico')], max_length=20, null=True, verbose_name='Tipo de Alimentación'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='fecha_actualizacion_ficha',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Actualización Ficha'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='ficha_tecnica_completa',
            field=models.BooleanField(default=False, verbose_name='Ficha Técnica Completa'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='frecuencia',
            field=models.CharField(blank=True, choices=[('50Hz', '50 Hz'), ('60Hz', '60 Hz'), ('50/60Hz', '50/60 Hz')], max_length=20, null=True, verbose_name='Frecuencia'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='frecuencia_mantenimiento',
            field=models.CharField(blank=True, choices=[('semanal', 'Semanal'), ('mensual', 'Mensual'), ('trimestral', 'Trimestral'), ('semestral', 'Semestral'), ('anual', 'Anual')], max_length=20, null=True, verbose_name='Frecuencia de Mantenimiento'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='humedad_max',
            field=models.IntegerField(blank=True, null=True, verbose_name='Humedad Máxima (%)'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='manual_operacion',
            field=models.FileField(blank=True, null=True, upload_to='documentos/manuales/', verbose_name='Manual de Operación'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='numero_serie',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de Serie'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Peso (kg)'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='presion_trabajo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Presión de Trabajo (Bar)'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='procedimientos_mantenimiento',
            field=models.TextField(blank=True, null=True, verbose_name='Procedimientos de Mantenimiento'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='temperatura_max',
            field=models.IntegerField(blank=True, null=True, verbose_name='Temperatura Máxima (°C)'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='temperatura_min',
            field=models.IntegerField(blank=True, null=True, verbose_name='Temperatura Mínima (°C)'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='tiempo_mantenimiento',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Tiempo Estimado Mantenimiento (horas)'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='ubicacion_especifica',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ubicación Específica'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='voltaje',
            field=models.CharField(blank=True, choices=[('110V', '110V'), ('220V', '220V'), ('380V', '380V'), ('440V', '440V'), ('110V/220V', '110V/220V'), ('220V/380V', '220V/380V'), ('otro', 'Otro')], max_length=20, null=True, verbose_name='Voltaje'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='fabricante',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='modelo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='responsable',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='serie',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='udb_numero',
            field=models.CharField(blank=True, help_text='Ejemplo: 1-22386', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='El número debe tener el formato 1-12345 (un dígito, guion, cinco dígitos)', regex='^\\d-\\d{5}$')], verbose_name='Número de Disposición'),
        ),
    ]
