# Generated by Django 4.2.20 on 2025-06-18 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0005_equipo_amperaje_equipo_caudal_aire_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='epp_requerido',
        ),
    ]
