# Generated by Django 4.2.20 on 2025-06-18 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0005_alter_material_options_and_more'),
        ('equipos', '0006_remove_equipo_epp_requerido'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='herramientas_necesarias',
            field=models.ManyToManyField(blank=True, limit_choices_to={'tipo__in': ['herramienta_manual', 'herramienta_electrica', 'herramienta_precision', 'herramienta_soldadura', 'herramienta_corte', 'herramienta_medicion', 'herramienta_seguridad', 'instrumento_laboratorio', 'herramienta_neumatica', 'herramienta_hidraulica', 'equipo_calibracion', 'instrumento_medicion_digital', 'herramienta_especial']}, related_name='equipos_que_lo_requieren', to='materiales.material', verbose_name='Herramientas Necesarias'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='materiales_necesarios',
            field=models.ManyToManyField(blank=True, limit_choices_to={'tipo__in': ['material_construccion', 'material_soldadura', 'consumible_general', 'quimico_laboratorio', 'lubricante', 'adhesivo_sellante', 'material_abrasivo', 'material_electrico', 'material_metalico', 'combustible', 'gas_industrial', 'pintura_recubrimiento']}, related_name='equipos_que_lo_usan', to='materiales.material', verbose_name='Materiales Necesarios'),
        ),
    ]
