# Generated by Django 4.2.20 on 2025-06-19 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0007_equipo_herramientas_necesarias_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='diagrama_neumatico',
            field=models.FileField(blank=True, null=True, upload_to='documentos/diagramas/', verbose_name='Diagrama Neumático'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='requiere_sistema_neumatico',
            field=models.BooleanField(default=False, verbose_name='¿Requiere Sistema Neumático?'),
        ),
    ]
