# Generated by Django 4.2.20 on 2025-06-11 01:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equipos', '0005_equipo_amperaje_equipo_caudal_aire_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcedimientoOperativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código POP')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título del Procedimiento')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('version', models.CharField(default='v1.0', max_length=10, verbose_name='Versión')),
                ('area', models.CharField(choices=[('soldadura', 'Soldadura'), ('maquinado', 'Maquinado'), ('fundicion', 'Fundición'), ('calidad', 'Control de Calidad'), ('seguridad', 'Seguridad Industrial'), ('mantenimiento', 'Mantenimiento')], max_length=20, verbose_name='Área')),
                ('tipo', models.CharField(choices=[('operativo', 'Operativo'), ('seguridad', 'Seguridad'), ('calidad', 'Calidad'), ('mantenimiento', 'Mantenimiento')], max_length=20, verbose_name='Tipo')),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=10, verbose_name='Prioridad')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('pendiente_aprobacion', 'Pendiente Aprobación'), ('en_capacitacion', 'En Capacitación'), ('validado_campo', 'Validado en Campo'), ('vencido', 'Vencido'), ('obsoleto', 'Obsoleto')], default='pendiente_aprobacion', max_length=25, verbose_name='Estado')),
                ('responsable', models.CharField(max_length=100, verbose_name='Responsable Principal')),
                ('equipo_asociado', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código de Equipo')),
                ('normativa', models.CharField(choices=[('ISO 9001', 'ISO 9001 - Sistema de Gestión de Calidad'), ('ISO 45001', 'ISO 45001 - Seguridad y Salud Ocupacional'), ('ISO 14001', 'ISO 14001 - Gestión Ambiental'), ('AWS D1.6', 'AWS D1.6 - Soldadura de Acero Inoxidable'), ('ASME BPVC', 'ASME BPVC - Código de Calderas y Recipientes'), ('OSHA 1910.146', 'OSHA 1910.146 - Espacios Confinados'), ('ASTM A48', 'ASTM A48 - Fundición de Hierro Gris'), ('ISO 17025', 'ISO 17025 - Competencia de Laboratorios'), ('ISO 55000', 'ISO 55000 - Gestión de Activos'), ('otra', 'Otra normativa')], max_length=50, verbose_name='Normativa Aplicable')),
                ('normativa_especifica', models.CharField(blank=True, help_text="Especificar si seleccionó 'Otra normativa'", max_length=200, null=True, verbose_name='Normativa Específica')),
                ('tiempo_estimado', models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1440)], verbose_name='Tiempo Estimado (minutos)')),
                ('frecuencia_aplicacion', models.CharField(choices=[('diaria', 'Diaria'), ('semanal', 'Semanal'), ('mensual', 'Mensual'), ('trimestral', 'Trimestral'), ('semestral', 'Semestral'), ('anual', 'Anual')], default='mensual', max_length=15, verbose_name='Frecuencia de Aplicación')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_ultima_revision', models.DateField(verbose_name='Última Revisión')),
                ('fecha_proxima_revision', models.DateField(verbose_name='Próxima Revisión')),
                ('fecha_vencimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Vencimiento')),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Aprobación')),
                ('objetivo', models.TextField(verbose_name='Objetivo del Procedimiento')),
                ('alcance', models.TextField(blank=True, null=True, verbose_name='Alcance')),
                ('materiales_herramientas', models.TextField(blank=True, null=True, verbose_name='Materiales y Herramientas Necesarios')),
                ('epp_requerido', models.TextField(blank=True, null=True, verbose_name='Equipos de Protección Personal')),
                ('procedimiento_paso_a_paso', models.TextField(verbose_name='Procedimiento Paso a Paso')),
                ('precauciones_seguridad', models.TextField(blank=True, null=True, verbose_name='Precauciones de Seguridad')),
                ('criterios_aceptacion', models.TextField(blank=True, null=True, verbose_name='Criterios de Aceptación')),
                ('registros_documentos', models.TextField(blank=True, null=True, verbose_name='Registros y Documentos Relacionados')),
                ('documento_pdf', models.FileField(blank=True, null=True, upload_to='procedimientos/documentos/', verbose_name='Documento PDF')),
                ('diagrama_flujo', models.ImageField(blank=True, null=True, upload_to='procedimientos/diagramas/', verbose_name='Diagrama de Flujo')),
                ('fotos_referencia', models.ImageField(blank=True, null=True, upload_to='procedimientos/fotos/', verbose_name='Fotos de Referencia')),
                ('es_critico', models.BooleanField(default=False, verbose_name='Procedimiento Crítico')),
                ('requiere_certificacion', models.BooleanField(default=False, verbose_name='Requiere Certificación')),
                ('numero_ejecuciones', models.PositiveIntegerField(default=0, verbose_name='Número de Ejecuciones')),
                ('eficiencia_promedio', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Eficiencia Promedio (%)')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pops_aprobados', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pops_creados', to=settings.AUTH_USER_MODEL)),
                ('equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procedimientos', to='equipos.equipo')),
            ],
            options={
                'verbose_name': 'Procedimiento Operativo Estándar',
                'verbose_name_plural': 'Procedimientos Operativos Estándar',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
