# Generated by Django 4.2.20 on 2025-06-11 02:11

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equipos', '0005_equipo_amperaje_equipo_caudal_aire_and_more'),
        ('operaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalisisRiesgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código de Riesgo')),
                ('descripcion', models.TextField(verbose_name='Descripción del Riesgo')),
                ('area', models.CharField(choices=[('soldadura', 'Soldadura'), ('maquinado', 'Maquinado'), ('fundicion', 'Fundición'), ('calidad', 'Control de Calidad'), ('mantenimiento', 'Mantenimiento'), ('almacen', 'Almacén'), ('oficinas', 'Oficinas'), ('laboratorio', 'Laboratorio')], max_length=20, verbose_name='Área')),
                ('tipo', models.CharField(choices=[('mecanico', 'Mecánico'), ('electrico', 'Eléctrico'), ('quimico', 'Químico'), ('termico', 'Térmico'), ('ergonomico', 'Ergonómico'), ('psicosocial', 'Psicosocial'), ('fisico', 'Físico'), ('biologico', 'Biológico'), ('ambiental', 'Ambiental')], max_length=20, verbose_name='Tipo de Riesgo')),
                ('probabilidad', models.IntegerField(help_text='1=Muy Baja, 2=Baja, 3=Media, 4=Alta, 5=Muy Alta', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Probabilidad (1-5)')),
                ('severidad', models.IntegerField(help_text='1=Insignificante, 2=Menor, 3=Moderada, 4=Mayor, 5=Catastrófica', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Severidad (1-5)')),
                ('riesgo_actual', models.IntegerField(editable=False, verbose_name='Riesgo Actual')),
                ('nivel_riesgo', models.CharField(choices=[('trivial', 'Trivial'), ('bajo', 'Bajo'), ('medio', 'Medio'), ('alto', 'Alto'), ('extremo', 'Extremo')], editable=False, max_length=10, verbose_name='Nivel de Riesgo')),
                ('estado', models.CharField(choices=[('identificado', 'Identificado'), ('en_tratamiento', 'En Tratamiento'), ('controlado', 'Controlado'), ('en_revision', 'En Revisión'), ('cerrado', 'Cerrado')], default='identificado', max_length=20, verbose_name='Estado')),
                ('responsable', models.CharField(max_length=100, verbose_name='Responsable')),
                ('fecha_identificacion', models.DateField(default=datetime.date.today, verbose_name='Fecha de Identificación')),
                ('fecha_revision', models.DateField(verbose_name='Fecha de Revisión')),
                ('medidas_control', models.TextField(blank=True, verbose_name='Medidas de Control Implementadas')),
                ('recursos_necesarios', models.TextField(blank=True, verbose_name='Recursos Necesarios')),
                ('plazo_implementacion', models.IntegerField(blank=True, null=True, verbose_name='Plazo de Implementación (días)')),
                ('fecha_ultima_revision', models.DateField(blank=True, null=True, verbose_name='Última Revisión')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('equipo_asociado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipos.equipo', verbose_name='Equipo Asociado')),
                ('identificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='riesgos_identificados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Análisis de Riesgo',
                'verbose_name_plural': 'Análisis de Riesgos',
                'ordering': ['-riesgo_actual', '-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='MedidaControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(verbose_name='Descripción de la Medida')),
                ('tipo_medida', models.CharField(choices=[('eliminacion', 'Eliminación'), ('sustitucion', 'Sustitución'), ('ingenieria', 'Controles de Ingeniería'), ('administrativo', 'Controles Administrativos'), ('epp', 'Equipos de Protección Personal')], max_length=20, verbose_name='Tipo de Medida')),
                ('estado', models.CharField(choices=[('planificada', 'Planificada'), ('en_implementacion', 'En Implementación'), ('implementada', 'Implementada'), ('verificada', 'Verificada'), ('no_efectiva', 'No Efectiva')], default='planificada', max_length=20, verbose_name='Estado')),
                ('fecha_planificada', models.DateField(verbose_name='Fecha Planificada')),
                ('fecha_implementacion', models.DateField(blank=True, null=True, verbose_name='Fecha de Implementación')),
                ('responsable', models.CharField(max_length=100, verbose_name='Responsable')),
                ('costo_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo Estimado')),
                ('eficacia_esperada', models.IntegerField(default=80, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Eficacia Esperada (%)')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('riesgo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medidas_control_detalle', to='operaciones.analisisriesgo')),
            ],
            options={
                'verbose_name': 'Medida de Control',
                'verbose_name_plural': 'Medidas de Control',
                'ordering': ['fecha_planificada'],
            },
        ),
    ]
