# Generated by Django 4.2.20 on 2025-06-11 02:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0002_analisisriesgo_medidacontrol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analisisriesgo',
            name='fecha_actualizacion',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Última Actualización'),
        ),
        migrations.AlterField(
            model_name='analisisriesgo',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación'),
        ),
    ]
