# Generated by Django 4.2.20 on 2025-06-11 04:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriarepuesto',
            options={'ordering': ['tipo_categoria', 'nombre'], 'verbose_name': 'Categoría de Repuesto', 'verbose_name_plural': 'Categorías de Repuestos'},
        ),
        migrations.AddField(
            model_name='categoriarepuesto',
            name='seccion_aplicable',
            field=models.CharField(blank=True, max_length=50, verbose_name='Sección Aplicable'),
        ),
        migrations.AddField(
            model_name='categoriarepuesto',
            name='tipo_categoria',
            field=models.CharField(choices=[('equipos', 'Equipos'), ('repuestos', 'Repuestos'), ('consumibles', 'Consumibles'), ('herramientas', 'Herramientas'), ('epp', 'EPP'), ('lubricantes', 'Lubricantes y Fluidos')], default='repuestos', max_length=15, verbose_name='Tipo de Categoría'),
        ),
        migrations.AddField(
            model_name='movimientostock',
            name='costo_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Costo Unitario del Movimiento'),
        ),
        migrations.AddField(
            model_name='movimientostock',
            name='numero_lote',
            field=models.CharField(blank=True, max_length=50, verbose_name='Número de Lote'),
        ),
        migrations.AddField(
            model_name='movimientostock',
            name='responsable_movimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_responsable', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='certificaciones',
            field=models.TextField(blank=True, help_text='ISO, API, ASME, etc.', verbose_name='Certificaciones'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='es_proveedor_critico',
            field=models.BooleanField(default=False, verbose_name='Proveedor Crítico'),
        ),
        migrations.AddField(
            model_name='repuesto',
            name='aplicacion_principal',
            field=models.TextField(blank=True, help_text='Descripción de la aplicación principal del repuesto', verbose_name='Aplicación Principal'),
        ),
        migrations.AddField(
            model_name='repuesto',
            name='bin_location',
            field=models.CharField(blank=True, help_text='Ubicación específica tipo bin', max_length=20, verbose_name='Ubicación Bin'),
        ),
        migrations.AddField(
            model_name='repuesto',
            name='certificaciones_requeridas',
            field=models.TextField(blank=True, verbose_name='Certificaciones Requeridas'),
        ),
        migrations.AddField(
            model_name='repuesto',
            name='codigo_activo_iso',
            field=models.CharField(blank=True, help_text='Código según norma ISO 14224 para activos industriales', max_length=50, verbose_name='Código de Activo ISO 14224'),
        ),
        migrations.AddField(
            model_name='repuesto',
            name='codigo_barras',
            field=models.CharField(blank=True, max_length=50, verbose_name='Código de Barras'),
        ),
        migrations.AddField(
            model_name='repuesto',
            name='codigo_qr',
            field=models.CharField(blank=True, max_length=100, verbose_name='Código QR'),
        ),
        migrations.AddField(
            model_name='repuesto',
            name='condiciones_almacenamiento',
            field=models.TextField(blank=True, verbose_name='Condiciones de Almacenamiento'),
        ),
        migrations.AddField(
            model_name='repuesto',
            name='costo_almacenamiento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo de Almacenamiento Anual'),
        ),
        migrations.AddField(
            model_name='repuesto',
            name='dimensiones',
            field=models.CharField(blank=True, max_length=200, verbose_name='Dimensiones'),
        ),
        migrations.AddField(
            model_name='repuesto',
            name='es_activo_critico',
            field=models.BooleanField(default=False, verbose_name='Activo Crítico'),
        ),
        migrations.AddField(
            model_name='repuesto',
            name='fecha_ultimo_inventario',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Último Inventario'),
        ),
        migrations.AddField(
            model_name='repuesto',
            name='frecuencia_uso',
            field=models.CharField(blank=True, max_length=50, verbose_name='Frecuencia de Uso'),
        ),
        migrations.AddField(
            model_name='repuesto',
            name='material_construccion',
            field=models.CharField(blank=True, max_length=100, verbose_name='Material de Construcción'),
        ),
        migrations.AddField(
            model_name='repuesto',
            name='msds',
            field=models.FileField(blank=True, null=True, upload_to='repuestos/msds/', verbose_name='Hoja de Datos de Seguridad (MSDS)'),
        ),
        migrations.AddField(
            model_name='repuesto',
            name='normas_aplicables',
            field=models.CharField(blank=True, help_text='ISO, ASTM, ASME, AWS, etc.', max_length=200, verbose_name='Normas Aplicables'),
        ),
        migrations.AddField(
            model_name='repuesto',
            name='notas_tecnicas',
            field=models.TextField(blank=True, verbose_name='Notas Técnicas'),
        ),
        migrations.AddField(
            model_name='repuesto',
            name='peso_unitario',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='Peso Unitario (kg)'),
        ),
        migrations.AddField(
            model_name='repuesto',
            name='requiere_manejo_especial',
            field=models.BooleanField(default=False, verbose_name='Requiere Manejo Especial'),
        ),
        migrations.AddField(
            model_name='repuesto',
            name='responsable_almacen',
            field=models.ForeignKey(blank=True, help_text='Responsable de almacén', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repuestos_responsable_almacen', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='repuesto',
            name='responsable_tecnico',
            field=models.ForeignKey(blank=True, help_text='Responsable técnico del repuesto', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repuestos_responsable_tecnico', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='repuesto',
            name='seccion_trabajo',
            field=models.CharField(blank=True, choices=[('S1', 'S1 - Soldadura, Corte y Perforación'), ('S2', 'S2 - Maquinado y Mecanizado'), ('S3', 'S3 - Prototipado'), ('S4', 'S4 - Plásticos'), ('S5', 'S5 - Fundición'), ('S6', 'S6 - Sujeción y Doblado'), ('S7', 'S7 - Transporte y Elevación'), ('A9', 'A9 - Tecnología de la Información'), ('ALM', 'Almacén General'), ('MAN', 'Mantenimiento'), ('CAL', 'Control de Calidad'), ('SEG', 'Seguridad Industrial')], max_length=5, verbose_name='Sección/Área de Trabajo'),
        ),
        migrations.AddField(
            model_name='repuesto',
            name='stock_seguridad',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Stock de Seguridad'),
        ),
        migrations.AddField(
            model_name='repuesto',
            name='vida_util_estimada',
            field=models.IntegerField(blank=True, null=True, verbose_name='Vida Útil Estimada (días)'),
        ),
        migrations.AlterField(
            model_name='movimientostock',
            name='tipo_movimiento',
            field=models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida'), ('ajuste', 'Ajuste'), ('devolucion', 'Devolución'), ('transferencia', 'Transferencia'), ('perdida', 'Pérdida'), ('inventario', 'Ajuste por Inventario'), ('merma', 'Merma'), ('rechazo_calidad', 'Rechazo por Calidad')], max_length=20, verbose_name='Tipo de Movimiento'),
        ),
        migrations.AlterField(
            model_name='repuesto',
            name='criticidad',
            field=models.CharField(choices=[('CRITICA', 'Crítica - Parada de producción'), ('IMPORTANTE', 'Importante - Afecta calidad'), ('MODERADA', 'Moderada - Afecta eficiencia'), ('BAJA', 'Baja - Sin impacto operacional')], default='MODERADA', max_length=15, verbose_name='Criticidad Operacional'),
        ),
        migrations.AlterField(
            model_name='repuesto',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('agotado', 'Agotado'), ('por_vencer', 'Por Vencer'), ('descontinuado', 'Descontinuado'), ('en_pedido', 'En Pedido'), ('en_transito', 'En Tránsito'), ('retenido_calidad', 'Retenido por Calidad')], default='disponible', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='repuesto',
            name='unidad_medida',
            field=models.CharField(choices=[('unidad', 'Unidad'), ('metro', 'Metro'), ('kilogramo', 'Kilogramo'), ('litro', 'Litro'), ('caja', 'Caja'), ('rollo', 'Rollo'), ('paquete', 'Paquete'), ('galón', 'Galón'), ('par', 'Par'), ('juego', 'Juego'), ('metros_lineales', 'Metros Lineales'), ('metros_cuadrados', 'Metros Cuadrados'), ('gramo', 'Gramo'), ('onza', 'Onza'), ('barra', 'Barra'), ('plancha', 'Plancha'), ('tubo', 'Tubo')], default='unidad', max_length=20, verbose_name='Unidad de Medida'),
        ),
        migrations.AddIndex(
            model_name='repuesto',
            index=models.Index(fields=['codigo'], name='inventario__codigo_74f284_idx'),
        ),
        migrations.AddIndex(
            model_name='repuesto',
            index=models.Index(fields=['codigo_activo_iso'], name='inventario__codigo__b0d119_idx'),
        ),
        migrations.AddIndex(
            model_name='repuesto',
            index=models.Index(fields=['seccion_trabajo', 'criticidad'], name='inventario__seccion_34218f_idx'),
        ),
        migrations.AddIndex(
            model_name='repuesto',
            index=models.Index(fields=['categoria', 'estado'], name='inventario__categor_cd521d_idx'),
        ),
    ]
