# Generated by Django 4.2.20 on 2025-06-11 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_categoriarepuesto_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repuesto',
            name='costo_ultima_compra',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='Costo Última Compra'),
        ),
        migrations.AlterField(
            model_name='repuesto',
            name='precio_promedio',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='Precio Promedio'),
        ),
    ]
