# Generated by Django 4.2.20 on 2025-06-11 15:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_alter_movimientostock_options_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='repuesto',
            name='inventario__codigo_74f284_idx',
        ),
        migrations.RemoveIndex(
            model_name='repuesto',
            name='inventario__codigo__b0d119_idx',
        ),
        migrations.RemoveIndex(
            model_name='repuesto',
            name='inventario__seccion_34218f_idx',
        ),
        migrations.RemoveIndex(
            model_name='repuesto',
            name='inventario__categor_cd521d_idx',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='es_proveedor_critico',
        ),
        migrations.AddField(
            model_name='proveedor',
            name='cargo_contacto',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cargo'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='categoria',
            field=models.CharField(choices=[('repuestos_mecanicos', 'Repuestos Mecánicos'), ('componentes_electronicos', 'Componentes Electrónicos'), ('herramientas', 'Herramientas'), ('materiales_soldadura', 'Materiales de Soldadura'), ('lubricantes', 'Lubricantes y Aceites'), ('elementos_seguridad', 'Elementos de Seguridad'), ('consumibles', 'Consumibles Generales'), ('servicios_especializados', 'Servicios Especializados')], default=1, max_length=30, verbose_name='Categoría Principal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proveedor',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=10, verbose_name='Código Postal'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='condiciones_pago',
            field=models.CharField(blank=True, max_length=100, verbose_name='Condiciones de Pago'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='departamento',
            field=models.CharField(default=1, max_length=100, verbose_name='Departamento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proveedor',
            name='descuento_general',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Descuento General (%)'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='dias_credito',
            field=models.PositiveIntegerField(default=0, verbose_name='Días de Crédito'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='email_secundario',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email Secundario'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('evaluacion', 'En Evaluación'), ('suspendido', 'Suspendido'), ('bloqueado', 'Bloqueado')], default='evaluacion', max_length=15, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Actualización'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='fecha_ultima_compra',
            field=models.DateField(blank=True, null=True, verbose_name='Última Compra'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='fecha_ultima_evaluacion',
            field=models.DateField(blank=True, null=True, verbose_name='Última Evaluación'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='licencia_funcionamiento',
            field=models.CharField(blank=True, max_length=50, verbose_name='Licencia de Funcionamiento'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='limite_credito',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Límite de Crédito'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='moneda_principal',
            field=models.CharField(default='BOB', max_length=20, verbose_name='Moneda Principal'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='nombre_comercial',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nombre Comercial'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='notas_internas',
            field=models.TextField(blank=True, verbose_name='Notas Internas'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='observaciones',
            field=models.TextField(blank=True, verbose_name='Observaciones'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='porcentaje_cumplimiento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='% Cumplimiento'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='registro_comercio',
            field=models.CharField(blank=True, max_length=50, verbose_name='Registro de Comercio'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='sitio_web',
            field=models.URLField(blank=True, verbose_name='Sitio Web'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='telefono_secundario',
            field=models.CharField(blank=True, max_length=20, verbose_name='Teléfono Secundario'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='tipo_proveedor',
            field=models.CharField(choices=[('nacional', 'Nacional'), ('internacional', 'Internacional'), ('local', 'Local'), ('distribuidor', 'Distribuidor'), ('fabricante', 'Fabricante')], default='ninguno', max_length=20, verbose_name='Tipo de Proveedor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proveedor',
            name='total_comprado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total Comprado'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='total_ordenes',
            field=models.PositiveIntegerField(default=0, verbose_name='Total de Órdenes'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='calificacion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Calificación (1-5)'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='ciudad',
            field=models.CharField(max_length=100, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='codigo',
            field=models.CharField(max_length=20, unique=True, verbose_name='Código de Proveedor'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='contacto_principal',
            field=models.CharField(max_length=100, verbose_name='Contacto Principal'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='direccion',
            field=models.TextField(verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email Principal'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nombre',
            field=models.CharField(max_length=200, verbose_name='Nombre/Razón Social'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono',
            field=models.CharField(max_length=20, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='tiempo_entrega_promedio',
            field=models.PositiveIntegerField(default=15, verbose_name='Tiempo Entrega Promedio (días)'),
        ),
    ]
