# Generated by Django 4.2.20 on 2025-06-11 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_remove_repuesto_inventario__codigo_74f284_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimientostock',
            options={'ordering': ['-fecha_movimiento'], 'verbose_name': 'Movimiento de Stock', 'verbose_name_plural': 'Movimientos de Stock'},
        ),
        migrations.RemoveIndex(
            model_name='movimientostock',
            name='inventario__repuest_714020_idx',
        ),
        migrations.RemoveIndex(
            model_name='movimientostock',
            name='inventario__fecha_m_8591d3_idx',
        ),
        migrations.RemoveIndex(
            model_name='movimientostock',
            name='inventario__usuario_522127_idx',
        ),
        migrations.RemoveIndex(
            model_name='movimientostock',
            name='inventario__estado_c5ff8f_idx',
        ),
        migrations.RemoveField(
            model_name='movimientostock',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='movimientostock',
            name='aprobado_por',
        ),
        migrations.RemoveField(
            model_name='movimientostock',
            name='fecha_aprobacion',
        ),
        migrations.RemoveField(
            model_name='movimientostock',
            name='notas_internas',
        ),
        migrations.RemoveField(
            model_name='movimientostock',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='movimientostock',
            name='requiere_aprobacion',
        ),
        migrations.AlterField(
            model_name='movimientostock',
            name='proveedor',
            field=models.ForeignKey(blank=True, help_text='Proveedor para movimientos de entrada', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.proveedor', verbose_name='Proveedor'),
        ),
    ]
