# Generated by Django 4.2.20 on 2025-06-11 23:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventario', '0006_alter_movimientostock_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimientostock',
            name='fecha_procesamiento',
        ),
        migrations.RemoveField(
            model_name='movimientostock',
            name='motivo_detalle',
        ),
        migrations.RemoveField(
            model_name='movimientostock',
            name='numero_factura',
        ),
        migrations.RemoveField(
            model_name='movimientostock',
            name='numero_orden',
        ),
        migrations.RemoveField(
            model_name='movimientostock',
            name='proveedor',
        ),
        migrations.RemoveField(
            model_name='movimientostock',
            name='ubicacion_destino',
        ),
        migrations.RemoveField(
            model_name='movimientostock',
            name='ubicacion_origen',
        ),
        migrations.AddField(
            model_name='movimientostock',
            name='observaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='movimientostock',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('procesado', 'Procesado'), ('cancelado', 'Cancelado')], default='procesado', max_length=15, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='movimientostock',
            name='motivo',
            field=models.CharField(choices=[('compra', 'Compra'), ('uso_mantenimiento', 'Uso en Mantenimiento'), ('uso_proyecto', 'Uso en Proyecto'), ('calibracion', 'Calibración'), ('prestamo', 'Préstamo'), ('devolucion_cliente', 'Devolución de Cliente'), ('inventario_fisico', 'Inventario Físico'), ('dano', 'Daño'), ('vencimiento', 'Vencimiento'), ('transferencia_interna', 'Transferencia Interna'), ('otro', 'Otro')], max_length=25, verbose_name='Motivo'),
        ),
        migrations.AlterField(
            model_name='movimientostock',
            name='repuesto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_stock', to='inventario.repuesto'),
        ),
        migrations.AlterField(
            model_name='movimientostock',
            name='tipo_movimiento',
            field=models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida'), ('ajuste_positivo', 'Ajuste Positivo'), ('ajuste_negativo', 'Ajuste Negativo'), ('transferencia_entrada', 'Transferencia - Entrada'), ('transferencia_salida', 'Transferencia - Salida'), ('devolucion', 'Devolución'), ('merma', 'Merma')], max_length=25, verbose_name='Tipo de Movimiento'),
        ),
        migrations.AlterField(
            model_name='movimientostock',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_stock', to=settings.AUTH_USER_MODEL),
        ),
    ]
