# Generated by Django 4.2.20 on 2025-06-11 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_remove_movimientostock_fecha_procesamiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientostock',
            name='fecha_procesamiento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Procesamiento'),
        ),
        migrations.AddField(
            model_name='movimientostock',
            name='motivo_detalle',
            field=models.TextField(blank=True, null=True, verbose_name='Detalle del Motivo'),
        ),
        migrations.AddField(
            model_name='movimientostock',
            name='ubicacion_destino',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ubicación Destino'),
        ),
    ]
