# Generated by Django 4.2.20 on 2025-06-11 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_movimientostock_fecha_procesamiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientostock',
            name='repuesto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='inventario.repuesto'),
        ),
    ]
