# Generated by Django 4.2.20 on 2025-06-13 03:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('capacitacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoTecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('tipo', models.CharField(choices=[('manual', 'Manual de Operación'), ('procedimiento', 'Procedimiento de Seguridad'), ('especificacion', 'Especificación Técnica'), ('guia', 'Guía de Mantenimiento'), ('normativa', 'Normativa/Reglamento'), ('ficha', 'Ficha Técnica'), ('catalogo', 'Catálogo de Productos'), ('instructivo', 'Instructivo'), ('reporte', 'Reporte Técnico'), ('protocolo', 'Protocolo de Seguridad')], default='manual', max_length=20, verbose_name='Tipo de Documento')),
                ('archivo_principal', models.FileField(blank=True, help_text='Archivo principal del documento', null=True, upload_to='documentos_tecnicos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'xlsx', 'pptx', 'txt', 'dwg', 'zip'])], verbose_name='Archivo Principal')),
                ('formato', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'Word (.docx)'), ('xlsx', 'Excel (.xlsx)'), ('pptx', 'PowerPoint (.pptx)'), ('txt', 'Texto (.txt)'), ('dwg', 'AutoCAD (.dwg)'), ('zip', 'Archivo Comprimido (.zip)')], default='pdf', max_length=10, verbose_name='Formato')),
                ('tamaño_archivo', models.PositiveIntegerField(blank=True, default=0, verbose_name='Tamaño (KB)')),
                ('contenido_html', models.TextField(blank=True, help_text='Contenido renderizable en web', verbose_name='Contenido HTML')),
                ('resumen_ejecutivo', models.TextField(blank=True, verbose_name='Resumen Ejecutivo')),
                ('palabras_clave', models.TextField(blank=True, help_text='Separadas por comas', verbose_name='Palabras Clave')),
                ('autor_documento', models.CharField(max_length=200, verbose_name='Autor del Documento')),
                ('revisor', models.CharField(blank=True, max_length=200, verbose_name='Revisor/Aprobador')),
                ('version', models.CharField(default='1.0', max_length=20, verbose_name='Versión')),
                ('codigo_documento', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Código de Documento')),
                ('dificultad', models.CharField(choices=[('basico', 'Básico'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado'), ('experto', 'Experto')], default='basico', max_length=20, verbose_name='Nivel de Complejidad')),
                ('confidencialidad', models.CharField(choices=[('publico', 'Público'), ('interno', 'Uso Interno'), ('confidencial', 'Confidencial'), ('restringido', 'Acceso Restringido')], default='interno', max_length=20, verbose_name='Nivel de Confidencialidad')),
                ('fecha_creacion_documento', models.DateField(blank=True, null=True, verbose_name='Fecha de Creación del Documento')),
                ('fecha_revision', models.DateField(blank=True, null=True, verbose_name='Fecha de Última Revisión')),
                ('fecha_vencimiento', models.DateField(blank=True, help_text='Cuándo debe revisarse', null=True, verbose_name='Fecha de Vencimiento')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('revision', 'En Revisión'), ('publicado', 'Publicado'), ('obsoleto', 'Obsoleto'), ('archivado', 'Archivado')], default='borrador', max_length=20, verbose_name='Estado')),
                ('requiere_actualizacion', models.BooleanField(default=False, verbose_name='Requiere Actualización')),
                ('es_obligatorio', models.BooleanField(default=False, verbose_name='Lectura Obligatoria')),
                ('objetivos', models.TextField(blank=True, help_text='Uno por línea', verbose_name='Objetivos')),
                ('aplicacion', models.TextField(blank=True, help_text='Dónde se aplica este documento', verbose_name='Área de Aplicación')),
                ('prerequisitos', models.TextField(blank=True, help_text='Uno por línea', verbose_name='Prerequisitos')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación en Sistema')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('fecha_publicacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Publicación')),
                ('vistas', models.PositiveIntegerField(default=0, verbose_name='Visualizaciones')),
                ('descargas', models.PositiveIntegerField(default=0, verbose_name='Descargas')),
                ('valoracion_promedio', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='Valoración Promedio')),
                ('autor_sistema', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_tecnicos_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_tecnicos', to='capacitacion.categoriacapacitacion', verbose_name='Categoría')),
                ('documentos_relacionados', models.ManyToManyField(blank=True, to='capacitacion.documentotecnico', verbose_name='Documentos Relacionados')),
            ],
            options={
                'verbose_name': 'Documento Técnico',
                'verbose_name_plural': 'Documentos Técnicos',
                'ordering': ['-fecha_modificacion'],
            },
        ),
        migrations.CreateModel(
            name='HistorialDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('crear', 'Documento Creado'), ('editar', 'Documento Editado'), ('publicar', 'Documento Publicado'), ('archivar', 'Documento Archivado'), ('ver', 'Documento Visualizado'), ('descargar', 'Documento Descargado'), ('cambiar_version', 'Versión Actualizada'), ('cambiar_estado', 'Estado Cambiado')], max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('version_anterior', models.CharField(blank=True, max_length=20)),
                ('version_nueva', models.CharField(blank=True, max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='capacitacion.documentotecnico')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Documento',
                'verbose_name_plural': 'Historial de Documentos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ValoracionDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valoracion', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Valoración del 1 al 5')),
                ('comentario', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valoraciones', to='capacitacion.documentotecnico')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Valoración de Documento',
                'verbose_name_plural': 'Valoraciones de Documentos',
                'ordering': ['-fecha'],
                'unique_together': {('documento', 'usuario')},
            },
        ),
        migrations.AddIndex(
            model_name='documentotecnico',
            index=models.Index(fields=['estado', 'categoria'], name='capacitacio_estado_e2cba8_idx'),
        ),
        migrations.AddIndex(
            model_name='documentotecnico',
            index=models.Index(fields=['tipo', 'confidencialidad'], name='capacitacio_tipo_efaf36_idx'),
        ),
        migrations.AddIndex(
            model_name='documentotecnico',
            index=models.Index(fields=['-fecha_modificacion'], name='capacitacio_fecha_m_f50daa_idx'),
        ),
        migrations.AddIndex(
            model_name='documentotecnico',
            index=models.Index(fields=['codigo_documento'], name='capacitacio_codigo__4b681c_idx'),
        ),
    ]
