# Generated by Django 4.2.20 on 2025-06-12 12:43

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SesionUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Inicio de Sesión')),
                ('fecha_fin', models.DateTimeField(blank=True, null=True, verbose_name='Fin de Sesión')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('activa', models.BooleanField(default=True, verbose_name='Sesión Activa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sesión de Usuario',
                'verbose_name_plural': 'Sesiones de Usuarios',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol_sistema', models.CharField(choices=[('administrador', 'Administrador'), ('operario', 'Operario')], default='operario', max_length=20, verbose_name='Rol del Sistema')),
                ('area_trabajo', models.CharField(blank=True, choices=[('soldadura', 'Soldadura'), ('maquinado', 'Maquinado'), ('prototipado', 'Prototipado'), ('plasticos', 'Plásticos'), ('fundicion', 'Fundición'), ('sujecion', 'Sujeción'), ('transporte', 'Transporte'), ('administracion', 'Administración'), ('calidad', 'Control de Calidad'), ('mantenimiento', 'Mantenimiento'), ('almacen', 'Almacén'), ('seguridad', 'Seguridad Industrial')], max_length=20, null=True, verbose_name='Área de Trabajo')),
                ('cargo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cargo/Puesto')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Formato de teléfono inválido', regex='^\\+?[0-9\\-\\s]{7,15}$')], verbose_name='Teléfono')),
                ('fecha_ingreso', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Ingreso')),
                ('ultima_actividad', models.DateTimeField(blank=True, null=True, verbose_name='Última Actividad')),
                ('activo', models.BooleanField(default=True, verbose_name='Usuario Activo')),
                ('recibir_notificaciones', models.BooleanField(default=True, verbose_name='Recibir Notificaciones')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='usuarios/avatars/', verbose_name='Avatar')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisados', to=settings.AUTH_USER_MODEL, verbose_name='Supervisor Directo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuarios',
                'ordering': ['user__first_name', 'user__last_name'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(choices=[('claro', 'Tema Claro'), ('oscuro', 'Tema Oscuro'), ('auto', 'Automático')], default='claro', max_length=10, verbose_name='Tema')),
                ('mostrar_ayuda', models.BooleanField(default=True, verbose_name='Mostrar Ayuda')),
                ('elementos_por_pagina', models.IntegerField(default=10, verbose_name='Elementos por Página')),
                ('notificar_mantenimiento', models.BooleanField(default=True, verbose_name='Notificar Mantenimiento')),
                ('notificar_stock_bajo', models.BooleanField(default=True, verbose_name='Notificar Stock Bajo')),
                ('notificar_fallas', models.BooleanField(default=True, verbose_name='Notificar Fallas')),
                ('widgets_dashboard', models.JSONField(blank=True, default=dict, verbose_name='Widgets Dashboard')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración de Usuario',
                'verbose_name_plural': 'Configuraciones de Usuario',
            },
        ),
    ]
