# Generated by Django 4.2.20 on 2025-06-12 23:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermisoSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código del Permiso')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Permiso')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('categoria', models.CharField(choices=[('usuarios', 'Gestión de Usuarios'), ('equipos', 'Gestión de Equipos'), ('inventario', 'Gestión de Inventario'), ('mantenimiento', 'Mantenimiento'), ('reportes', 'Reportes y Análisis'), ('configuracion', 'Configuración del Sistema'), ('seguridad', 'Seguridad Industrial'), ('operaciones', 'Operaciones Diarias')], max_length=20, verbose_name='Categoría')),
                ('es_critico', models.BooleanField(default=False, help_text='No se puede desactivar', verbose_name='Permiso Crítico')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Permiso del Sistema',
                'verbose_name_plural': 'Permisos del Sistema',
                'ordering': ['categoria', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='RolPersonalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre del Rol')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('color', models.CharField(default='#6b7280', help_text='Color hexadecimal', max_length=7, verbose_name='Color')),
                ('icono', models.CharField(default='bi-person', help_text='Clase de Bootstrap Icon', max_length=50, verbose_name='Icono')),
                ('es_sistema', models.BooleanField(default=False, help_text='No se puede eliminar', verbose_name='Rol del Sistema')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roles_creados', to=settings.AUTH_USER_MODEL)),
                ('permisos', models.ManyToManyField(blank=True, to='usuarios.permisosistema', verbose_name='Permisos')),
            ],
            options={
                'verbose_name': 'Rol Personalizado',
                'verbose_name_plural': 'Roles Personalizados',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='HistorialRoles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('crear_rol', 'Rol Creado'), ('editar_rol', 'Rol Editado'), ('eliminar_rol', 'Rol Eliminado'), ('asignar_permiso', 'Permiso Asignado'), ('remover_permiso', 'Permiso Removido'), ('cambiar_rol_usuario', 'Rol de Usuario Cambiado')], max_length=20, verbose_name='Acción')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('datos_antiguos', models.JSONField(blank=True, default=dict, verbose_name='Datos Anteriores')),
                ('datos_nuevos', models.JSONField(blank=True, default=dict, verbose_name='Datos Nuevos')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('permiso_afectado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.permisosistema')),
                ('rol_afectado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.rolpersonalizado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_roles', to=settings.AUTH_USER_MODEL)),
                ('usuario_afectado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cambios_rol', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Roles',
                'verbose_name_plural': 'Historial de Roles',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='rol_personalizado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.rolpersonalizado', verbose_name='Rol Personalizado'),
        ),
    ]
