# Generated by Django 4.2.20 on 2025-06-13 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_permisosistema_rolpersonalizado_historialroles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialroles',
            name='accion',
            field=models.CharField(choices=[('crear_rol', 'Rol Creado'), ('editar_rol', 'Rol Editado'), ('eliminar_rol', 'Rol Eliminado'), ('asignar_permiso', 'Permiso Asignado'), ('remover_permiso', 'Permiso Removido'), ('cambiar_rol_usuario', 'Rol de Usuario Cambiado'), ('crear_respaldo', 'Respaldo Creado'), ('descargar_respaldo', 'Respaldo Descargado'), ('eliminar_respaldo', 'Respaldo Eliminado')], max_length=20, verbose_name='Acción'),
        ),
    ]
