# Generated by Django 4.2.20 on 2025-06-12 02:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalisisEquipos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_analisis', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Análisis')),
                ('total_equipos', models.PositiveIntegerField(default=0, verbose_name='Total de Equipos')),
                ('equipos_operativos', models.PositiveIntegerField(default=0, verbose_name='Equipos Operativos')),
                ('equipos_mantenimiento', models.PositiveIntegerField(default=0, verbose_name='Equipos en Mantenimiento')),
                ('equipos_fuera_servicio', models.PositiveIntegerField(default=0, verbose_name='Equipos Fuera de Servicio')),
                ('disponibilidad_promedio', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Disponibilidad Promedio (%)')),
                ('tiempo_promedio_mantenimiento', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Tiempo Promedio Mantenimiento (horas)')),
                ('costo_mantenimiento_estimado', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Costo Mantenimiento Estimado')),
            ],
            options={
                'verbose_name': 'Análisis de Equipos',
                'verbose_name_plural': 'Análisis de Equipos',
                'ordering': ['-fecha_analisis'],
            },
        ),
        migrations.CreateModel(
            name='ReporteGenerado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título del Reporte')),
                ('tipo_reporte', models.CharField(choices=[('equipos_general', 'Reporte General de Equipos'), ('equipos_estado', 'Reporte por Estado de Equipos'), ('equipos_mantenimiento', 'Reporte de Mantenimiento'), ('equipos_ubicacion', 'Reporte por Ubicación'), ('equipos_criticidad', 'Reporte por Criticidad'), ('equipos_valor', 'Reporte de Valor de Equipos'), ('equipos_antiguedad', 'Reporte de Antigüedad'), ('materiales_stock', 'Reporte de Stock de Materiales'), ('materiales_movimientos', 'Reporte de Movimientos'), ('herramientas_calibracion', 'Reporte de Calibración')], max_length=30, verbose_name='Tipo de Reporte')),
                ('formato', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV')], max_length=10, verbose_name='Formato')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Generación')),
                ('parametros_filtros', models.JSONField(blank=True, default=dict, verbose_name='Parámetros de Filtros')),
                ('total_registros', models.PositiveIntegerField(default=0, verbose_name='Total de Registros')),
                ('archivo_generado', models.FileField(blank=True, null=True, upload_to='reportes/', verbose_name='Archivo Generado')),
                ('tiempo_generacion', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Tiempo de Generación (segundos)')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_generados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reporte Generado',
                'verbose_name_plural': 'Reportes Generados',
                'ordering': ['-fecha_generacion'],
            },
        ),
    ]
