# Generated by Django 4.2.20 on 2025-06-12 04:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equipos', '0005_equipo_amperaje_equipo_caudal_aire_and_more'),
        ('reportes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroFalla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_falla', models.CharField(max_length=20, unique=True, verbose_name='Código de Falla')),
                ('descripcion_falla', models.TextField(verbose_name='Descripción de la Falla')),
                ('fecha_ocurrencia', models.DateTimeField(verbose_name='Fecha de Ocurrencia')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('severidad', models.CharField(choices=[('critica', 'Crítica'), ('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], max_length=10, verbose_name='Severidad')),
                ('estado', models.CharField(choices=[('identificada', 'Identificada'), ('analisis', 'En Análisis'), ('solucionada', 'Solucionada'), ('pendiente', 'Pendiente'), ('cerrada', 'Cerrada')], default='identificada', max_length=15, verbose_name='Estado')),
                ('tipo_falla', models.CharField(choices=[('mecanica', 'Mecánica'), ('electrica', 'Eléctrica'), ('hidraulica', 'Hidráulica'), ('neumatica', 'Neumática'), ('software', 'Software'), ('operacional', 'Operacional'), ('desgaste', 'Desgaste Natural'), ('calibracion', 'Descalibración'), ('contaminacion', 'Contaminación'), ('sobrecarga', 'Sobrecarga'), ('vibracion', 'Vibración Excesiva'), ('temperatura', 'Problema Térmico')], max_length=20, verbose_name='Tipo de Falla')),
                ('causa_raiz', models.CharField(blank=True, choices=[('mantenimiento_inadecuado', 'Mantenimiento Inadecuado'), ('desgaste_natural', 'Desgaste Natural'), ('operacion_incorrecta', 'Operación Incorrecta'), ('sobrecarga_equipo', 'Sobrecarga del Equipo'), ('falta_lubricacion', 'Falta de Lubricación'), ('contaminacion_ambiente', 'Contaminación Ambiental'), ('defecto_fabricacion', 'Defecto de Fabricación'), ('instalacion_incorrecta', 'Instalación Incorrecta'), ('falta_capacitacion', 'Falta de Capacitación'), ('componente_defectuoso', 'Componente Defectuoso'), ('condiciones_ambientales', 'Condiciones Ambientales Adversas'), ('fatiga_material', 'Fatiga del Material'), ('corrosion', 'Corrosión'), ('interferencia_electromagnetica', 'Interferencia Electromagnética'), ('desconocida', 'Causa Desconocida')], max_length=30, null=True, verbose_name='Causa Raíz')),
                ('causa_inmediata', models.TextField(blank=True, null=True, verbose_name='Causa Inmediata')),
                ('condiciones_operacion', models.TextField(blank=True, null=True, verbose_name='Condiciones de Operación')),
                ('tiempo_parada', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Tiempo de Parada (horas)')),
                ('costo_reparacion', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Costo de Reparación')),
                ('produccion_perdida', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Producción Perdida')),
                ('indice_criticidad', models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Índice de Criticidad')),
                ('supervisor', models.CharField(blank=True, max_length=100, null=True, verbose_name='Supervisor')),
                ('solucion_aplicada', models.TextField(blank=True, null=True, verbose_name='Solución Aplicada')),
                ('fecha_solucion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Solución')),
                ('tiempo_reparacion', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Tiempo de Reparación (horas)')),
                ('repuestos_utilizados', models.TextField(blank=True, null=True, verbose_name='Repuestos Utilizados')),
                ('acciones_preventivas', models.TextField(blank=True, null=True, verbose_name='Acciones Preventivas')),
                ('recomendaciones', models.TextField(blank=True, null=True, verbose_name='Recomendaciones')),
                ('foto_falla', models.ImageField(blank=True, null=True, upload_to='fallas/fotos/', verbose_name='Foto de la Falla')),
                ('reporte_tecnico', models.FileField(blank=True, null=True, upload_to='fallas/reportes/', verbose_name='Reporte Técnico')),
                ('requiere_seguimiento', models.BooleanField(default=False, verbose_name='Requiere Seguimiento')),
                ('fecha_seguimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Seguimiento')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('asignado_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fallas_asignadas', to=settings.AUTH_USER_MODEL)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fallas_registradas', to='equipos.equipo')),
                ('reportado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fallas_reportadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Falla',
                'verbose_name_plural': 'Registros de Fallas',
                'ordering': ['-fecha_ocurrencia'],
            },
        ),
        migrations.AlterField(
            model_name='reportegenerado',
            name='tipo_reporte',
            field=models.CharField(choices=[('equipos_general', 'Reporte General de Equipos'), ('equipos_estado', 'Reporte por Estado de Equipos'), ('equipos_mantenimiento', 'Reporte de Mantenimiento'), ('equipos_ubicacion', 'Reporte por Ubicación'), ('equipos_criticidad', 'Reporte por Criticidad'), ('equipos_valor', 'Reporte de Valor de Equipos'), ('equipos_antiguedad', 'Reporte de Antigüedad'), ('materiales_stock', 'Reporte de Stock de Materiales'), ('materiales_movimientos', 'Reporte de Movimientos'), ('herramientas_calibracion', 'Reporte de Calibración'), ('analisis_fallas', 'Análisis de Fallas')], max_length=30, verbose_name='Tipo de Reporte'),
        ),
        migrations.CreateModel(
            name='SeguimientoFalla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_accion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Acción')),
                ('tipo_accion', models.CharField(choices=[('diagnostico', 'Diagnóstico'), ('reparacion_temporal', 'Reparación Temporal'), ('reparacion_definitiva', 'Reparación Definitiva'), ('reemplazo_componente', 'Reemplazo de Componente'), ('ajuste_parametros', 'Ajuste de Parámetros'), ('prueba_funcionamiento', 'Prueba de Funcionamiento'), ('verificacion_solucion', 'Verificación de Solución'), ('cierre_falla', 'Cierre de Falla')], max_length=25, verbose_name='Tipo de Acción')),
                ('descripcion_accion', models.TextField(verbose_name='Descripción de la Acción')),
                ('tiempo_empleado', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Tiempo Empleado (horas)')),
                ('costo_accion', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo de la Acción')),
                ('resultado', models.TextField(blank=True, null=True, verbose_name='Resultado Obtenido')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('falla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='reportes.registrofalla')),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Seguimiento de Falla',
                'verbose_name_plural': 'Seguimientos de Fallas',
                'ordering': ['-fecha_accion'],
            },
        ),
    ]
