# Generated by Django 4.2.20 on 2025-06-11 21:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de Categoría')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('tipo_categoria', models.CharField(choices=[('herramientas', 'Herramientas'), ('materiales', 'Materiales'), ('consumibles', 'Consumibles'), ('equipos_medicion', 'Equipos de Medición'), ('seguridad', 'Elementos de Seguridad'), ('mantenimiento', 'Mantenimiento')], default='materiales', max_length=20, verbose_name='Tipo de Categoría')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Categoría de Material',
                'verbose_name_plural': 'Categorías de Materiales',
                'ordering': ['tipo_categoria', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True, verbose_name='Código Interno')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Material')),
                ('descripcion', models.TextField(verbose_name='Descripción Detallada')),
                ('tipo', models.CharField(choices=[('herramienta', 'Herramienta'), ('material', 'Material'), ('consumible', 'Consumible'), ('equipo_medicion', 'Equipo de Medición'), ('epp', 'Elemento de Protección Personal')], max_length=20, verbose_name='Tipo')),
                ('marca', models.CharField(blank=True, max_length=100, verbose_name='Marca')),
                ('modelo', models.CharField(blank=True, max_length=100, verbose_name='Modelo')),
                ('numero_parte', models.CharField(blank=True, max_length=100, verbose_name='Número de Parte')),
                ('codigo_barras', models.CharField(blank=True, max_length=50, verbose_name='Código de Barras')),
                ('stock_actual', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Stock Actual')),
                ('stock_minimo', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Stock Mínimo')),
                ('stock_maximo', models.DecimalField(decimal_places=2, default=100, max_digits=10, verbose_name='Stock Máximo')),
                ('punto_reorden', models.DecimalField(decimal_places=2, default=5, max_digits=10, verbose_name='Punto de Reorden')),
                ('unidad_medida', models.CharField(choices=[('unidad', 'Unidad'), ('metro', 'Metro'), ('kilogramo', 'Kilogramo'), ('litro', 'Litro'), ('caja', 'Caja'), ('paquete', 'Paquete'), ('rollo', 'Rollo'), ('par', 'Par'), ('juego', 'Juego')], default='unidad', max_length=20, verbose_name='Unidad de Medida')),
                ('ubicacion', models.CharField(blank=True, max_length=100, verbose_name='Ubicación en Almacén')),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Precio Unitario')),
                ('criticidad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=10, verbose_name='Criticidad')),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('agotado', 'Agotado'), ('bajo_stock', 'Stock Bajo'), ('en_pedido', 'En Pedido'), ('descontinuado', 'Descontinuado')], default='disponible', max_length=15, verbose_name='Estado')),
                ('es_herramienta_critica', models.BooleanField(default=False, verbose_name='Herramienta Crítica')),
                ('requiere_calibracion', models.BooleanField(default=False, verbose_name='Requiere Calibración')),
                ('fecha_ultima_calibracion', models.DateField(blank=True, null=True, verbose_name='Última Calibración')),
                ('frecuencia_calibracion', models.IntegerField(blank=True, null=True, verbose_name='Frecuencia Calibración (días)')),
                ('requiere_mantenimiento', models.BooleanField(default=False, verbose_name='Requiere Mantenimiento')),
                ('fecha_ultimo_mantenimiento', models.DateField(blank=True, null=True, verbose_name='Último Mantenimiento')),
                ('frecuencia_mantenimiento', models.IntegerField(blank=True, null=True, verbose_name='Frecuencia Mantenimiento (días)')),
                ('fecha_vencimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Vencimiento')),
                ('fecha_ultima_compra', models.DateField(blank=True, null=True, verbose_name='Fecha Última Compra')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='materiales/fotos/', verbose_name='Foto del Material')),
                ('ficha_tecnica', models.FileField(blank=True, null=True, upload_to='materiales/fichas/', verbose_name='Ficha Técnica')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materiales', to='materiales.categoriamaterial')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiales',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código de Proveedor')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre/Razón Social')),
                ('contacto_principal', models.CharField(max_length=100, verbose_name='Contacto Principal')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Principal')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('evaluacion', 'En Evaluación')], default='activo', max_length=15, verbose_name='Estado')),
                ('calificacion', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Calificación (1-5)')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_movimiento', models.CharField(max_length=20, unique=True, verbose_name='Número de Movimiento')),
                ('tipo_movimiento', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida'), ('ajuste_positivo', 'Ajuste Positivo'), ('ajuste_negativo', 'Ajuste Negativo'), ('transferencia', 'Transferencia'), ('devolucion', 'Devolución'), ('merma', 'Merma')], max_length=20, verbose_name='Tipo de Movimiento')),
                ('motivo', models.CharField(choices=[('compra', 'Compra'), ('uso_proyecto', 'Uso en Proyecto'), ('mantenimiento', 'Mantenimiento'), ('calibracion', 'Calibración'), ('prestamo', 'Préstamo'), ('devolucion_cliente', 'Devolución de Cliente'), ('inventario_fisico', 'Inventario Físico'), ('daño', 'Daño'), ('vencimiento', 'Vencimiento'), ('otro', 'Otro')], max_length=20, verbose_name='Motivo')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad')),
                ('stock_anterior', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Stock Anterior')),
                ('stock_nuevo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Stock Nuevo')),
                ('costo_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Costo Unitario')),
                ('costo_total', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Costo Total')),
                ('fecha_movimiento', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha del Movimiento')),
                ('documento_referencia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Documento de Referencia')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesado', 'Procesado'), ('cancelado', 'Cancelado')], default='procesado', max_length=15, verbose_name='Estado')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='materiales.material')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_materiales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento de Material',
                'verbose_name_plural': 'Movimientos de Materiales',
                'ordering': ['-fecha_movimiento'],
            },
        ),
        migrations.AddField(
            model_name='material',
            name='proveedor_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiales_principales', to='materiales.proveedor'),
        ),
    ]
