# Generated by Django 4.2.20 on 2025-06-11 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriamaterial',
            name='tipo_categoria',
            field=models.CharField(choices=[('materiales_construccion', 'Materiales de Construcción'), ('materiales_soldadura', 'Materiales de Soldadura'), ('consumibles_laboratorio', 'Consumibles de Laboratorio'), ('quimicos_reactivos', 'Químicos y Reactivos'), ('lubricantes_fluidos', 'Lubricantes y Fluidos'), ('materiales_electricos', 'Materiales Eléctricos'), ('materiales_metalicos', 'Materiales Metálicos'), ('combustibles_gases', 'Combustibles y Gases'), ('pinturas_recubrimientos', 'Pinturas y Recubrimientos'), ('adhesivos_sellantes', 'Adhesivos y Sellantes'), ('abrasivos_pulimentos', 'Abrasivos y Pulimentos'), ('materiales_proteccion', 'Materiales de Protección')], default='materiales_construccion', max_length=30, verbose_name='Tipo de Categoría'),
        ),
        migrations.AlterField(
            model_name='material',
            name='tipo',
            field=models.CharField(choices=[('material_construccion', 'Material de Construcción'), ('material_soldadura', 'Material de Soldadura'), ('consumible_general', 'Consumible General'), ('quimico_laboratorio', 'Químico de Laboratorio'), ('lubricante', 'Lubricante'), ('adhesivo_sellante', 'Adhesivo/Sellante'), ('material_abrasivo', 'Material Abrasivo'), ('material_electrico', 'Material Eléctrico'), ('material_metalico', 'Material Metálico'), ('combustible', 'Combustible'), ('gas_industrial', 'Gas Industrial'), ('pintura_recubrimiento', 'Pintura/Recubrimiento')], max_length=25, verbose_name='Tipo'),
        ),
    ]
