# Generated by Django 4.2.20 on 2025-06-11 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0003_add_caracteristicas_especiales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ubicación en Almacén'),
        ),
    ]
