# Generated by Django 4.2.20 on 2025-06-12 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0004_corregir_campos_faltantes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Material/Herramienta', 'verbose_name_plural': 'Materiales y Herramientas'},
        ),
        migrations.AlterField(
            model_name='categoriamaterial',
            name='tipo_categoria',
            field=models.CharField(choices=[('materiales_construccion', 'Materiales de Construcción'), ('materiales_soldadura', 'Materiales de Soldadura'), ('consumibles_laboratorio', 'Consumibles de Laboratorio'), ('quimicos_reactivos', 'Químicos y Reactivos'), ('lubricantes_fluidos', 'Lubricantes y Fluidos'), ('materiales_electricos', 'Materiales Eléctricos'), ('materiales_metalicos', 'Materiales Metálicos'), ('combustibles_gases', 'Combustibles y Gases'), ('pinturas_recubrimientos', 'Pinturas y Recubrimientos'), ('adhesivos_sellantes', 'Adhesivos y Sellantes'), ('abrasivos_pulimentos', 'Abrasivos y Pulimentos'), ('materiales_proteccion', 'Materiales de Protección'), ('herramientas_manuales', 'Herramientas Manuales'), ('herramientas_electricas', 'Herramientas Eléctricas'), ('instrumentos_medicion', 'Instrumentos de Medición'), ('herramientas_precision', 'Herramientas de Precisión'), ('herramientas_corte', 'Herramientas de Corte'), ('equipos_laboratorio', 'Equipos de Laboratorio'), ('herramientas_soldadura_eq', 'Herramientas de Soldadura'), ('herramientas_neumaticas', 'Herramientas Neumáticas'), ('herramientas_hidraulicas', 'Herramientas Hidráulicas'), ('instrumentos_calibracion', 'Instrumentos de Calibración'), ('herramientas_seguridad', 'Herramientas de Seguridad'), ('herramientas_especiales', 'Herramientas Especializadas')], default='materiales_construccion', max_length=30, verbose_name='Tipo de Categoría'),
        ),
        migrations.AlterField(
            model_name='material',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('agotado', 'Agotado'), ('bajo_stock', 'Stock Bajo'), ('en_pedido', 'En Pedido'), ('descontinuado', 'Descontinuado'), ('en_uso', 'En Uso'), ('mantenimiento', 'En Mantenimiento'), ('calibracion', 'En Calibración')], default='disponible', max_length=15, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='material',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='materiales/fotos/', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='material',
            name='nombre',
            field=models.CharField(max_length=200, verbose_name='Nombre del Material/Herramienta'),
        ),
        migrations.AlterField(
            model_name='material',
            name='tipo',
            field=models.CharField(choices=[('material_construccion', 'Material de Construcción'), ('material_soldadura', 'Material de Soldadura'), ('consumible_general', 'Consumible General'), ('quimico_laboratorio', 'Químico de Laboratorio'), ('lubricante', 'Lubricante'), ('adhesivo_sellante', 'Adhesivo/Sellante'), ('material_abrasivo', 'Material Abrasivo'), ('material_electrico', 'Material Eléctrico'), ('material_metalico', 'Material Metálico'), ('combustible', 'Combustible'), ('gas_industrial', 'Gas Industrial'), ('pintura_recubrimiento', 'Pintura/Recubrimiento'), ('herramienta_manual', 'Herramienta Manual'), ('herramienta_electrica', 'Herramienta Eléctrica'), ('herramienta_precision', 'Herramienta de Precisión'), ('herramienta_soldadura', 'Herramienta de Soldadura'), ('herramienta_corte', 'Herramienta de Corte'), ('herramienta_medicion', 'Herramienta de Medición'), ('herramienta_seguridad', 'Herramienta de Seguridad'), ('instrumento_laboratorio', 'Instrumento de Laboratorio'), ('herramienta_neumatica', 'Herramienta Neumática'), ('herramienta_hidraulica', 'Herramienta Hidráulica'), ('equipo_calibracion', 'Equipo de Calibración'), ('instrumento_medicion_digital', 'Instrumento de Medición Digital'), ('herramienta_especial', 'Herramienta Especializada')], max_length=30, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='material',
            name='unidad_medida',
            field=models.CharField(choices=[('unidad', 'Unidad'), ('metro', 'Metro'), ('kilogramo', 'Kilogramo'), ('litro', 'Litro'), ('caja', 'Caja'), ('paquete', 'Paquete'), ('rollo', 'Rollo'), ('par', 'Par'), ('juego', 'Juego'), ('kit', 'Kit'), ('set', 'Set'), ('pieza', 'Pieza')], default='unidad', max_length=20, verbose_name='Unidad de Medida'),
        ),
    ]
