# Generated by Django 5.2.3 on 2025-09-14 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0005_alter_material_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('en_uso', 'En Uso'), ('mantenimiento', 'En Mantenimiento'), ('calibracion', 'En Calibración'), ('defectuoso', 'Defectuoso'), ('quebrado', 'Quebrado/Roto'), ('desgastado', 'Desgastado'), ('obsoleto', 'Obsoleto'), ('prestado', 'Prestado'), ('extraviado', 'Extraviado'), ('descontinuado', 'Descontinuado')], default='disponible', max_length=15, verbose_name='Estado'),
        ),
    ]
