# Generated by Django 4.2.20 on 2025-06-10 03:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equipos', '0005_equipo_amperaje_equipo_caudal_aire_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_plan', models.CharField(max_length=20, unique=True, verbose_name='Código del Plan')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Plan')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('tipo_mantenimiento', models.CharField(choices=[('preventivo', 'Preventivo'), ('correctivo', 'Correctivo'), ('predictivo', 'Predictivo'), ('autonomo', 'Autónomo')], max_length=20, verbose_name='Tipo de Mantenimiento')),
                ('frecuencia', models.CharField(choices=[('diario', 'Diario'), ('semanal', 'Semanal'), ('quincenal', 'Quincenal'), ('mensual', 'Mensual'), ('bimestral', 'Bimestral'), ('trimestral', 'Trimestral'), ('semestral', 'Semestral'), ('anual', 'Anual')], max_length=20, verbose_name='Frecuencia')),
                ('duracion_estimada', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Duración Estimada (horas)')),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=10, verbose_name='Prioridad')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('pausado', 'Pausado'), ('inactivo', 'Inactivo'), ('revision', 'En Revisión')], default='activo', max_length=15, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('proxima_ejecucion', models.DateField(blank=True, null=True, verbose_name='Próxima Ejecución')),
                ('ultima_ejecucion', models.DateField(blank=True, null=True, verbose_name='Última Ejecución')),
                ('costo_estimado', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Costo Estimado')),
                ('procedimiento_documento', models.FileField(blank=True, null=True, upload_to='mantenimiento/procedimientos/', verbose_name='Documento de Procedimiento')),
                ('lista_verificacion', models.FileField(blank=True, null=True, upload_to='mantenimiento/listas/', verbose_name='Lista de Verificación')),
                ('requiere_parada_equipo', models.BooleanField(default=False, verbose_name='Requiere Parada de Equipo')),
                ('herramientas_especiales', models.TextField(blank=True, null=True, verbose_name='Herramientas Especiales')),
                ('materiales_requeridos', models.TextField(blank=True, null=True, verbose_name='Materiales Requeridos')),
                ('numero_ejecuciones', models.PositiveIntegerField(default=0, verbose_name='Número de Ejecuciones')),
                ('tiempo_promedio_ejecucion', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Tiempo Promedio (horas)')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_mantenimiento', to='equipos.equipo')),
                ('responsable_principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planes_responsable', to=settings.AUTH_USER_MODEL)),
                ('responsables_secundarios', models.ManyToManyField(blank=True, related_name='planes_colaborador', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plan de Mantenimiento',
                'verbose_name_plural': 'Planes de Mantenimiento',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='TareaMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la Tarea')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('orden', models.PositiveIntegerField(default=1, verbose_name='Orden')),
                ('duracion_estimada', models.DecimalField(decimal_places=0, default=30, max_digits=5, verbose_name='Duración Estimada (minutos)')),
                ('es_critica', models.BooleanField(default=False, verbose_name='Tarea Crítica')),
                ('requiere_verificacion', models.BooleanField(default=False, verbose_name='Requiere Verificación')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En Progreso'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=15, verbose_name='Estado')),
                ('instrucciones', models.TextField(blank=True, null=True, verbose_name='Instrucciones Específicas')),
                ('herramientas_necesarias', models.TextField(blank=True, null=True, verbose_name='Herramientas Necesarias')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='mantenimiento.planmantenimiento')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tarea de Mantenimiento',
                'verbose_name_plural': 'Tareas de Mantenimiento',
                'ordering': ['orden', 'nombre'],
            },
        ),
    ]
