# Generated by Django 4.2.20 on 2025-06-10 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0002_repuestocritico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planmantenimiento',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('activo', 'Activo'), ('pausado', 'Pausado'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='borrador', help_text='Estado actual del plan de mantenimiento', max_length=20, verbose_name='Estado'),
        ),
    ]
