# Generated by Django 4.2.20 on 2025-06-19 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0004_ordentrabajo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planmantenimiento',
            name='duracion_estimada',
        ),
        migrations.AddField(
            model_name='planmantenimiento',
            name='duracion_estimada_rango',
            field=models.CharField(choices=[('corta', 'Corta (1-4 horas)'), ('media', 'Media (4-8 horas)'), ('larga', 'Larga (8-16 horas)'), ('extendida', 'Extendida (16+ horas)'), ('multiple_dias', 'Múltiples días')], default='media', help_text='Rango aproximado de tiempo que podría tomar el mantenimiento', max_length=50, verbose_name='Estimación de Duración'),
        ),
        migrations.AddField(
            model_name='planmantenimiento',
            name='duracion_real',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Se registra después de completar el mantenimiento', max_digits=7, null=True, verbose_name='Duración Real (horas)'),
        ),
    ]
